### ISSUE TITLE
Rack 2.0.1 breaks `bundle install`

### ISSUE THREAD

**Issue by jaybrueder** [litaio/chef-lita#33]
As Rack 2.0.1 now requires Ruby 2.2.2, the converging with the lita-cookbook fails:

```
================================================================================
           Error executing action `run` on resource 'execute[bundle-install-lita]'
           ================================================================================
​
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '5'
           ---- Begin output of bundle install --path vendor/ --binstubs bin ----
           STDOUT: Fetching gem metadata from https://rubygems.org/.........
           Fetching version metadata from https://rubygems.org/..
           Resolving dependencies...
           Using bundler 1.12.5
           Installing chronic 0.10.2
           Installing multi_json 1.12.1
           Installing eventmachine 1.2.0.1 with native extensions
           Installing multipart-post 2.0.0
           Installing websocket-extensions 0.1.2
           Installing rack 2.0.1
​
           Gem::InstallError: rack requires Ruby version >= 2.2.2.
           Installing i18n 0.7.0
           Installing ice_nine 0.11.2
           Installing json 2.0.1 with native extensions
           Installing mixlib-shellout 2.2.6
           Installing mini_portile2 2.1.0
           Installing pkg-config 1.1.7
           Installing socksify 1.7.0
           Installing terminal-table 1.6.0
           Installing thor 0.19.1
           Installing puma 3.4.0 with native extensions
           Installing rb-readline 0.5.3
           Installing redis 3.3.0
           Installing ruby_cowsay 0.1.1
           Installing dogapi 1.22.0
           Installing faraday 0.9.2
           Installing websocket-driver 0.6.4 with native extensions
           An error occurred while installing rack (2.0.1), and Bundler cannot continue.
           Make sure that `gem install rack -v '2.0.1'` succeeds before bundling.
           STDERR:
           ---- End output of bundle install --path vendor/ --binstubs bin ----
           Ran bundle install --path vendor/ --binstubs bin returned 5
​
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:49:in `block in run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:47:in `run_action'
​
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/lita/recipes/install.rb
​
            76: execute "bundle-install-lita" do
            77:   action :nothing
            78:   command "bundle install --path vendor/ --binstubs bin"
            79:   cwd node["lita"]["install_dir"]
            80:   user node["lita"]["daemon_user"]
            81:   notifies :run, "execute[chown-cleanup]", :immediately
            82:   notifies :restart, "service[lita]"
            83: end
            84:
​
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/lita/recipes/install.rb:76:in `from_file'
​
           execute("bundle-install-lita") do
             action [:nothing]
             retries 0
             retry_delay 2
             default_guard_interpreter :execute
             command "bundle install --path vendor/ --binstubs bin"
             backup 5
             cwd "/opt/lita"
             returns 0
             user "nobody"
             declared_type :execute
             cookbook_name "lita"
             recipe_name "install"
           end
​
           Platform:
           ---------
           x86_64-linux
​
       Recipe: ntp::default
         * service[ntp] action restart
           - restart service service[ntp]
       Recipe: ntp::apparmor
         * service[apparmor] action restart
           - restart service service[apparmor]
       Recipe: jenkins::_master_war
         * runit_service[jenkins] action restart (up to date)
       Recipe: <Dynamically Defined Resource>
         * service[lita] action restart
​
           ================================================================================
           Error executing action `restart` on resource 'service[lita]'
           ================================================================================
​
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/bin/sv restart /etc/service/lita ----
           STDOUT: fail: /etc/service/lita: unable to change to service directory: file does not exist
           STDERR:
           ---- End output of /usr/bin/sv restart /etc/service/lita ----
           Ran /usr/bin/sv restart /etc/service/lita returned 1
​
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
​
           Compiled Resource:
           ------------------
           # Declared in
​
           service("lita") do
             provider Chef::Provider::Service::Simple
             action [:nothing]
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "lita"
             pattern "lita"
             start_command "/usr/bin/sv start /etc/service/lita"
             stop_command "/usr/bin/sv stop /etc/service/lita"
             status_command "/usr/bin/sv status /etc/service/lita"
             restart_command "/usr/bin/sv restart /etc/service/lita"
           end
​
           Platform:
           ---------
           x86_64-linux
1 Comment Collaps
```

Freezing the Rack version in the `/opt/lita/Gemfile` does the trick:

```
$ cat /opt/lita/Gemfile
source "https://rubygems.org"

gem "rack", "1.6.4"
gem "lita", "~> 4.7.0"

gem "lita-slack"
```

**Comment by harlanbarnes** [comment]
Hi there - Thanks for the report. Sorry for the delay, I was out of town.

Unfortunately, I can't think of a perfect fix for this.

I think the good news is that likely only affects people that use the "auto" value of `default["lita"]["ruby_install_type"]`. That is, folks who control their own ruby version are likely to also control their own Gemfile template and/or control tightly the `default["lita"]["gems"]` attribute.

The bad news is those who use the "auto" value are the ones I'm most concerned about.

Here's the ideas I considered and discarded:
1. Pinning rack in the `default["lita"]["gems"]` attribute. This would work in some scenarios (like using all defaults) but if anyone overrode that value in roles or wrappers, they'd have to know to add the rack dependency to their list too ... which has us back to this problem.
2. Doing some sort of "smart-ish" default where if the ruby version was "auto" then determine if the latest version of ruby is 2.2.2 or greater and then just add into the gems attribute there. This seems like the closest fit, but it also seems like it's pretty hackish. (this cookbook already has it's fair share of hackery 😄 ) And if we did, we'd probably want to bump the minor version just in case someone was betting on the current default "auto" ruby versions.
3. Just making the default "auto" ruby version for everything to be 2.2.2 or higher. I think we should do this, but we'd probably need to bump (at least) the minor version for that.
4. Just document it on the README and release a PATCH so that it shows up on Supermarket, etc.

I think 3 and 4 are no-brainers. I'd like to think about 2 a little more.

And, of course, any input on this is greatly appreciated.

**Comment by harlanbarnes** [comment]
It looks like @jimmycuadra has changed the Gemfile in Lita for the next release that will handle the Rack issue ... so I'm not going to change anything here after all.

https://github.com/litaio/lita/commit/fda3a80f73c31975cd32cb45e6a0f1499b401a7e
